using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using AstraGraph.Core;

namespace AstraGraph.JIT;

/// <summary>
/// Compiles Astra Intermediate Representation (IR) into high-performance C# source code
/// ready for in-memory Roslyn compilation.
/// </summary>
public sealed class IrToCSharpCompiler
{
    public static string GenerateCSharp(IrProgram program, out string generatedClassName)
    {
        ArgumentNullException.ThrowIfNull(program);

        var classSuffix = program.Id.Value.ToString("N");
        generatedClassName = $"AstraJitRunner_{classSuffix}";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using AstraGraph.Core;");
        sb.AppendLine("using AstraGraph.VM;");
        sb.AppendLine();
        sb.AppendLine("namespace AstraGraph.JIT.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public sealed class {generatedClassName}");
        sb.AppendLine("    {");

        var allFunctions = new List<IrFunction>(program.Functions);
        foreach (var ep in program.EntryPoints)
        {
            if (!allFunctions.Contains(ep))
            {
                allFunctions.Add(ep);
            }
        }

        foreach (var func in allFunctions)
        {
            EmitFunction(sb, func);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitFunction(StringBuilder sb, IrFunction func)
    {
        var sanitizedName = SanitizeIdentifier(func.Name);
        var regCount = Math.Max(func.RegisterCount, 1);

        sb.AppendLine($"        public AstraValue Execute_{sanitizedName}(");
        sb.AppendLine("            AstraValue[]? initialRegisters,");
        sb.AppendLine("            IVmHostServices services,");
        sb.AppendLine("            ExecutionBudget budget)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var r = new AstraValue[{regCount}];");
        sb.AppendLine("            if (initialRegisters != null)");
        sb.AppendLine("            {");
        sb.AppendLine("                Array.Copy(initialRegisters, r, Math.Min(initialRegisters.Length, r.Length));");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            goto block_{func.EntryBlock.Id};");
        sb.AppendLine();

        foreach (var block in func.Blocks)
        {
            sb.AppendLine($"        block_{block.Id}:");
            sb.AppendLine("            {");
            sb.AppendLine("                budget?.Tick();");

            foreach (var instr in block.Instructions)
            {
                EmitInstruction(sb, instr);
            }

            if (block.Terminator != null)
            {
                EmitTerminator(sb, block, block.Terminator);
            }
            else
            {
                sb.AppendLine("                return AstraValue.Null;");
            }

            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitInstruction(StringBuilder sb, IrInstruction instr)
    {
        var dest = instr.Destination?.Index ?? -1;

        switch (instr.OpCode)
        {
            case IrOpCode.Nop:
                break;

            case IrOpCode.LoadConst:
                if (dest >= 0)
                {
                    var operand = instr.Operands?[0];
                    if (operand is IrConstant c)
                    {
                        EmitConstantAssignment(sb, dest, c.Value);
                    }
                    else
                    {
                        sb.AppendLine($"                r[{dest}] = AstraValue.Null;");
                    }
                }
                break;

            case IrOpCode.Add:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine("                {");
                sb.AppendLine($"                    var l = r[{r1}]; var ri = r[{r2}];");
                sb.AppendLine("                    if (l.Type == AstraValueType.Double || ri.Type == AstraValueType.Double)");
                sb.AppendLine($"                        r[{dest}] = AstraValue.FromDouble(l.AsDouble() + ri.AsDouble());");
                sb.AppendLine("                    else if (l.Type == AstraValueType.Object || ri.Type == AstraValueType.Object)");
                sb.AppendLine($"                        r[{dest}] = AstraValue.FromString((l.AsString() ?? \"\") + (ri.AsString() ?? \"\"));");
                sb.AppendLine("                    else");
                sb.AppendLine($"                        r[{dest}] = AstraValue.FromInt64(l.AsInt64() + ri.AsInt64());");
                sb.AppendLine("                }");
                break;
            }

            case IrOpCode.Sub:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine("                {");
                sb.AppendLine($"                    var l = r[{r1}]; var ri = r[{r2}];");
                sb.AppendLine($"                    r[{dest}] = (l.Type == AstraValueType.Double || ri.Type == AstraValueType.Double)");
                sb.AppendLine("                        ? AstraValue.FromDouble(l.AsDouble() - ri.AsDouble())");
                sb.AppendLine("                        : AstraValue.FromInt64(l.AsInt64() - ri.AsInt64());");
                sb.AppendLine("                }");
                break;
            }

            case IrOpCode.Mul:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine("                {");
                sb.AppendLine($"                    var l = r[{r1}]; var ri = r[{r2}];");
                sb.AppendLine($"                    r[{dest}] = (l.Type == AstraValueType.Double || ri.Type == AstraValueType.Double)");
                sb.AppendLine("                        ? AstraValue.FromDouble(l.AsDouble() * ri.AsDouble())");
                sb.AppendLine("                        : AstraValue.FromInt64(l.AsInt64() * ri.AsInt64());");
                sb.AppendLine("                }");
                break;
            }

            case IrOpCode.Div:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine("                {");
                sb.AppendLine($"                    var l = r[{r1}]; var ri = r[{r2}];");
                sb.AppendLine($"                    r[{dest}] = (l.Type == AstraValueType.Double || ri.Type == AstraValueType.Double)");
                sb.AppendLine("                        ? AstraValue.FromDouble(l.AsDouble() / ri.AsDouble())");
                sb.AppendLine("                        : AstraValue.FromInt64(l.AsInt64() / ri.AsInt64());");
                sb.AppendLine("                }");
                break;
            }

            case IrOpCode.Mod:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine($"                r[{dest}] = AstraValue.FromInt64(r[{r1}].AsInt64() % r[{r2}].AsInt64());");
                break;
            }

            case IrOpCode.Neg:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                sb.AppendLine($"                r[{dest}] = r[{r1}].Type == AstraValueType.Double ? AstraValue.FromDouble(-r[{r1}].AsDouble()) : AstraValue.FromInt64(-r[{r1}].AsInt64());");
                break;
            }

            case IrOpCode.CmpEq:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(r[{r1}].Equals(r[{r2}]));");
                break;
            }

            case IrOpCode.CmpNe:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(!r[{r1}].Equals(r[{r2}]));");
                break;
            }

            case IrOpCode.CmpLt:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine("                {");
                sb.AppendLine($"                    var l = r[{r1}]; var ri = r[{r2}];");
                sb.AppendLine($"                    r[{dest}] = AstraValue.FromBool((l.Type == AstraValueType.Double || ri.Type == AstraValueType.Double)");
                sb.AppendLine("                        ? l.AsDouble() < ri.AsDouble() : l.AsInt64() < ri.AsInt64());");
                sb.AppendLine("                }");
                break;
            }

            case IrOpCode.CmpLe:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine("                {");
                sb.AppendLine($"                    var l = r[{r1}]; var ri = r[{r2}];");
                sb.AppendLine($"                    r[{dest}] = AstraValue.FromBool((l.Type == AstraValueType.Double || ri.Type == AstraValueType.Double)");
                sb.AppendLine("                        ? l.AsDouble() <= ri.AsDouble() : l.AsInt64() <= ri.AsInt64());");
                sb.AppendLine("                }");
                break;
            }

            case IrOpCode.CmpGt:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine("                {");
                sb.AppendLine($"                    var l = r[{r1}]; var ri = r[{r2}];");
                sb.AppendLine($"                    r[{dest}] = AstraValue.FromBool((l.Type == AstraValueType.Double || ri.Type == AstraValueType.Double)");
                sb.AppendLine("                        ? l.AsDouble() > ri.AsDouble() : l.AsInt64() > ri.AsInt64());");
                sb.AppendLine("                }");
                break;
            }

            case IrOpCode.CmpGe:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine("                {");
                sb.AppendLine($"                    var l = r[{r1}]; var ri = r[{r2}];");
                sb.AppendLine($"                    r[{dest}] = AstraValue.FromBool((l.Type == AstraValueType.Double || ri.Type == AstraValueType.Double)");
                sb.AppendLine("                        ? l.AsDouble() >= ri.AsDouble() : l.AsInt64() >= ri.AsInt64());");
                sb.AppendLine("                }");
                break;
            }

            case IrOpCode.And:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(r[{r1}].AsBool() && r[{r2}].AsBool());");
                break;
            }

            case IrOpCode.Or:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                var r2 = ((IrRegister)instr.Operands![1]).Index;
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(r[{r1}].AsBool() || r[{r2}].AsBool());");
                break;
            }

            case IrOpCode.Not:
            {
                var r1 = ((IrRegister)instr.Operands![0]).Index;
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(!r[{r1}].AsBool());");
                break;
            }

            case IrOpCode.CallNative:
            {
                var method = EscapeString(instr.StringPayload ?? string.Empty);
                var argsList = new List<string>();
                if (instr.Operands != null)
                {
                    foreach (var op in instr.Operands)
                    {
                        var argReg = ((IrRegister)op).Index;
                        argsList.Add($"r[{argReg}]");
                    }
                }
                var argsArray = argsList.Count > 0 ? $"new AstraValue[] {{ {string.Join(", ", argsList)} }}" : "Array.Empty<AstraValue>()";
                if (dest >= 0)
                {
                    sb.AppendLine($"                r[{dest}] = services.CallNative(\"{method}\", {argsArray});");
                }
                else
                {
                    sb.AppendLine($"                services.CallNative(\"{method}\", {argsArray});");
                }
                break;
            }

            case IrOpCode.LoadVariable:
            {
                var varName = EscapeString(instr.StringPayload ?? string.Empty);
                sb.AppendLine($"                r[{dest}] = services.GetVariable(SymbolId.Empty, \"{varName}\");");
                break;
            }

            case IrOpCode.StoreVariable:
            {
                var varName = EscapeString(instr.StringPayload ?? string.Empty);
                var valReg = ((IrRegister)instr.Operands![0]).Index;
                sb.AppendLine($"                services.SetVariable(SymbolId.Empty, \"{varName}\", r[{valReg}]);");
                break;
            }

            case IrOpCode.GetComponent:
            {
                var entityReg = ((IrRegister)instr.Operands![0]).Index;
                var compName = EscapeString(instr.StringPayload ?? string.Empty);
                sb.AppendLine($"                r[{dest}] = services.GetComponent(r[{entityReg}].AsEntityUid(), \"{compName}\");");
                break;
            }

            case IrOpCode.HasComponent:
            {
                var entityReg = ((IrRegister)instr.Operands![0]).Index;
                var compName = EscapeString(instr.StringPayload ?? string.Empty);
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(services.HasComponent(r[{entityReg}].AsEntityUid(), \"{compName}\"));");
                break;
            }

            case IrOpCode.SetComponentField:
            {
                var entityReg = ((IrRegister)instr.Operands![0]).Index;
                var valReg = ((IrRegister)instr.Operands[1]).Index;
                var fieldKey = EscapeString(instr.StringPayload ?? string.Empty);
                sb.AppendLine($"                services.SetComponentField(r[{entityReg}].AsEntityUid(), \"{fieldKey}\", r[{valReg}]);");
                break;
            }

            case IrOpCode.StructMake:
                sb.AppendLine($"                r[{dest}] = AstraValues.MakeStruct(\"{EscapeString(instr.StringPayload ?? string.Empty)}\");");
                break;

            case IrOpCode.StructCopy:
                sb.AppendLine($"                r[{dest}] = AstraValues.CopyValue(r[{((IrRegister)instr.Operands![0]).Index}]);");
                break;

            case IrOpCode.SetField:
                sb.AppendLine($"                r[{dest}] = AstraValues.SetField(r[{((IrRegister)instr.Operands![0]).Index}], \"{EscapeString(instr.StringPayload ?? string.Empty)}\", r[{((IrRegister)instr.Operands[1]).Index}]);");
                break;

            case IrOpCode.ListMake:
                sb.AppendLine($"                r[{dest}] = AstraValues.MakeList();");
                break;

            case IrOpCode.CollectionAdd:
                sb.AppendLine($"                r[{dest}] = AstraValues.CollectionAdd(r[{((IrRegister)instr.Operands![0]).Index}], r[{((IrRegister)instr.Operands[1]).Index}]);");
                break;

            case IrOpCode.CollectionSet:
                sb.AppendLine($"                r[{dest}] = AstraValues.CollectionSet(r[{((IrRegister)instr.Operands![0]).Index}], r[{((IrRegister)instr.Operands[1]).Index}].AsInt32(), r[{((IrRegister)instr.Operands[2]).Index}]);");
                break;

            case IrOpCode.CollectionContains:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(AstraValues.CollectionContains(r[{((IrRegister)instr.Operands![0]).Index}], r[{((IrRegister)instr.Operands[1]).Index}]));");
                break;

            case IrOpCode.CollectionIntersects:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(AstraValues.CollectionIntersects(r[{((IrRegister)instr.Operands![0]).Index}], r[{((IrRegister)instr.Operands[1]).Index}]));");
                break;

            case IrOpCode.CollectionContainsAll:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool(AstraValues.CollectionContainsAll(r[{((IrRegister)instr.Operands![0]).Index}], r[{((IrRegister)instr.Operands[1]).Index}]));");
                break;

            case IrOpCode.Select:
                sb.AppendLine($"                r[{dest}] = r[{((IrRegister)instr.Operands![0]).Index}].AsBool() ? r[{((IrRegister)instr.Operands[1]).Index}] : r[{((IrRegister)instr.Operands[2]).Index}];");
                break;

            case IrOpCode.CollectionRemove:
                sb.AppendLine($"                r[{dest}] = AstraValues.CollectionRemove(r[{((IrRegister)instr.Operands![0]).Index}], r[{((IrRegister)instr.Operands[1]).Index}].AsInt32());");
                break;

            case IrOpCode.PersistentIdNew:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromPersistentId(PersistentObjectId.New());");
                break;

            default:
                break;
        }
    }

    private static void EmitTerminator(StringBuilder sb, IrBasicBlock block, IrInstruction instr)
    {
        switch (instr.OpCode)
        {
            case IrOpCode.BranchIf:
            {
                var condReg = ((IrRegister)instr.Operands![0]).Index;
                var trueBlock = block.Successors[0];
                var falseBlock = block.Successors.Count > 1 ? block.Successors[1] : null;
                if (falseBlock != null)
                {
                    sb.AppendLine($"                if (r[{condReg}].AsBool()) goto block_{trueBlock.Id}; else goto block_{falseBlock.Id};");
                }
                else
                {
                    sb.AppendLine($"                if (r[{condReg}].AsBool()) goto block_{trueBlock.Id};");
                }
                break;
            }

            case IrOpCode.Jump:
            {
                var target = block.Successors[0];
                sb.AppendLine($"                goto block_{target.Id};");
                break;
            }

            case IrOpCode.Return:
            {
                if (instr.Operands != null && instr.Operands.Count > 0)
                {
                    var retReg = ((IrRegister)instr.Operands[0]).Index;
                    sb.AppendLine($"                return r[{retReg}];");
                }
                else
                {
                    sb.AppendLine("                return AstraValue.Null;");
                }
                break;
            }

            default:
                sb.AppendLine("                return AstraValue.Null;");
                break;
        }
    }

    private static void EmitConstantAssignment(StringBuilder sb, int dest, object? value)
    {
        switch (value)
        {
            case null:
                sb.AppendLine($"                r[{dest}] = AstraValue.Null;");
                break;
            case bool b:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromBool({(b ? "true" : "false")});");
                break;
            case long l:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromInt64({l}L);");
                break;
            case int i:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromInt64({i}L);");
                break;
            case double d:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromDouble({d.ToString("R", CultureInfo.InvariantCulture)});");
                break;
            case float f:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromDouble({f.ToString("R", CultureInfo.InvariantCulture)});");
                break;
            case string s:
                sb.AppendLine($"                r[{dest}] = AstraValue.FromString(\"{EscapeString(s)}\");");
                break;
            default:
                sb.AppendLine($"                r[{dest}] = AstraValue.Null;");
                break;
        }
    }

    private static string EscapeString(string s) =>
        s.Replace("\\", "\\\\", StringComparison.Ordinal)
         .Replace("\"", "\\\"", StringComparison.Ordinal)
         .Replace("\r", "\\r", StringComparison.Ordinal)
         .Replace("\n", "\\n", StringComparison.Ordinal);

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder();
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
            {
                sb.Append(ch);
            }
            else
            {
                sb.Append('_');
            }
        }
        return sb.ToString();
    }
}
