<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AstraGraph.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AstraGraph.Core\AstraGraph.Core.csproj" />
    <ProjectReference Include="..\AstraGraph.State\AstraGraph.State.csproj" />
  </ItemGroup>

</Project>
