<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AstraGraph.Editor.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AstraGraph.Core\AstraGraph.Core.csproj" />
    <ProjectReference Include="..\AstraGraph.Binding\AstraGraph.Binding.csproj" />
  </ItemGroup>

</Project>
