using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Web;

namespace AstraGraph.Editor.Bridge;

/// <summary>
/// Deep-link context for opening Astra Studio at a specific location.
/// </summary>
public sealed record StudioLaunchContext(
    string? EntityUid = null,
    string? GraphId = null,
    string? NodeId = null,
    string? PinId = null,
    string? Action = null,
    string? ErrorCode = null);

/// <summary>
/// Cross-platform browser launcher for Astra Studio Web.
/// Builds a safe startup URL embedding nonce and optional deep-link parameters.
/// </summary>
public static class BrowserLauncher
{
    /// <summary>
    /// Constructs the Studio URL and opens it in the system default browser.
    /// </summary>
    /// <param name="port">Local loopback port the bridge is listening on.</param>
    /// <param name="nonce">One-time launch nonce generated by <see cref="SessionNonceManager"/>.</param>
    /// <param name="context">Optional deep-link context to focus a specific entity/graph/node.</param>
    public static void OpenStudio(int port, string nonce, StudioLaunchContext? context = null)
    {
        string url = BuildStudioUrl(port, nonce, context);
        OpenUrl(url);
    }

    /// <summary>
    /// Builds the launch URL without opening the browser (useful for testing or copying).
    /// </summary>
    public static string BuildStudioUrl(int port, string nonce, StudioLaunchContext? context = null)
    {
        ArgumentOutOfRangeException.ThrowIfLessThanOrEqual(port, 0);
        ArgumentException.ThrowIfNullOrWhiteSpace(nonce);

        var sb = new StringBuilder();
        sb.Append($"http://127.0.0.1:{port}/?nonce={Uri.EscapeDataString(nonce)}");

        if (context == null)
            return sb.ToString();

        if (!string.IsNullOrEmpty(context.EntityUid))
            sb.Append($"&entity={Uri.EscapeDataString(context.EntityUid)}");
        if (!string.IsNullOrEmpty(context.GraphId))
            sb.Append($"&graph={Uri.EscapeDataString(context.GraphId)}");
        if (!string.IsNullOrEmpty(context.NodeId))
            sb.Append($"&node={Uri.EscapeDataString(context.NodeId)}");
        if (!string.IsNullOrEmpty(context.PinId))
            sb.Append($"&pin={Uri.EscapeDataString(context.PinId)}");
        if (!string.IsNullOrEmpty(context.Action))
            sb.Append($"&action={Uri.EscapeDataString(context.Action)}");
        if (!string.IsNullOrEmpty(context.ErrorCode))
            sb.Append($"&error={Uri.EscapeDataString(context.ErrorCode)}");

        return sb.ToString();
    }

    /// <summary>
    /// Opens the given URL in the system default browser cross-platform.
    /// </summary>
    public static void OpenUrl(string url)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(url);

        try
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                Process.Start(new ProcessStartInfo("cmd", $"/c start \"\" \"{url}\"")
                {
                    CreateNoWindow = true,
                    UseShellExecute = false
                });
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                Process.Start("open", url);
            }
            else
            {
                // Linux / Unix
                Process.Start("xdg-open", url);
            }
        }
        catch (Exception ex)
        {
            throw new BrowserLaunchException($"Failed to open browser for URL '{url}': {ex.Message}", ex);
        }
    }
}

/// <summary>
/// Thrown when the system browser cannot be launched.
/// </summary>
public sealed class BrowserLaunchException : Exception
{
    public BrowserLaunchException(string message, Exception? inner = null) : base(message, inner) { }
}
