<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AstraGraph.Editor.InGame</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AstraGraph.Core\AstraGraph.Core.csproj" />
    <ProjectReference Include="..\AstraGraph.Editor.Bridge\AstraGraph.Editor.Bridge.csproj" />
    <ProjectReference Include="..\AstraGraph.Editor.Protocol\AstraGraph.Editor.Protocol.csproj" />
  </ItemGroup>

</Project>
